# Generated by Django 4.2 on 2024-04-16 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hybridapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='caseName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='KeyPairs',
        ),
    ]
