# Generated by Django 4.2.13 on 2024-06-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hybridapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptinfo',
            name='ip_details',
        ),
    ]
