# Generated by Django 4.2 on 2024-05-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hybridapp', '0002_alter_case_caseid_alter_case_casename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('case_name', models.CharField(max_length=100)),
                ('case_info', models.TextField(blank=True)),
                ('case_file', models.FileField(blank=True, upload_to='encrypted_files/')),
                ('case_data', models.BinaryField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
