# Generated by Django 4.2 on 2024-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybridapp', '0003_encryptcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptcase',
            name='case_data',
            field=models.BinaryField(blank=True),
        ),
    ]
