# Generated by Django 4.2 on 2024-05-11 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hybridapp', '0004_alter_encryptcase_case_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='encryption_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='encryptcase',
            name='encryption_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='encryption_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
