# Generated by Django 4.2 on 2024-05-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybridapp', '0005_case_encryption_date_encryptcase_encryption_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
