# Generated by Django 4.2 on 2024-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybridapp', '0006_alter_encryptedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptcase',
            name='case_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
