# Generated by Django 4.2 on 2024-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybridapp', '0007_alter_encryptcase_case_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptcase',
            name='case_data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='encryptcase',
            name='case_file',
            field=models.FileField(upload_to=''),
        ),
    ]
